### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [theorange7/tdd-vidbits#4]
(Meets Expectations) Overall, nice work.

Remember to make smaller commits with concise messages that summarize the changes. Also, prefer string interpolation to addition.

Again, nice use of es6 features and `async`/`await`, your code is clean and easy to follow!

**Comment by theorange7** [comment]
Thanks cj! :) I was rushing so I didn't really bother on the commits hahaha. My apologies. 

Also, prefer string interpolation to addition. < you mean the ${} syntax?

**Comment by theorange7** [comment]
Oh its alright, I saw the example you gave in the other issue. thank you!
